name: Test repository dispatch

on:
  repository_dispatch:
    types: [update-catalog]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar payload
        env:
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "$PAYLOAD"
